var TRANSLATIONS = Object.freeze({
  en: Object.freeze({
    documentTitle: "Cosmic Catchers",
    gameAria: "Cosmic Catchers game",
    brandKicker: "Arcade field / desktop edition",
    gameTitle: "COSMIC CATCHERS",
    cosmicTitle: "Cosmic",
    catchersTitle: "Catchers",
    scoreLabel: "Score",
    phaseLabel: "Phase",
    patternLabel: "Pattern",
    streakLabel: "Streak",
    welcomeKicker: "Welcome back, pilot",
    readyIntro: "The disks follow fixed lines. Flip each monster to the correct color before they reach the target.",
    readyIntroEasy: "Two disks follow fixed lines. Flip each monster to the correct color before they reach the target.",
    readyIntroHard: "Three disks follow fixed lines. Flip all three monsters to the correct color before they reach the targets.",
    greenRuleTitle: "TOP / GREEN",
    greenRuleText: "The green monster catches the green disk.",
    redRuleTitle: "BOTTOM / RED",
    redRuleText: "The red monster catches the red disk.",
    startButton: "Start the round",
    enteringField: "Entering the cosmic field",
    readyNoteEasy: "A / \u2190 flips the left lane \xB7 D / \u2192 flips the right lane",
    readyNoteHard: "A / \u2190 left \xB7 S / \u2193 middle \xB7 D / \u2192 right",
    helpEasy: "P PAUSE \xB7 A/\u2190 LEFT \xB7 D/\u2192 RIGHT \xB7 CLICK A SIDE TO FLIP",
    helpHard: "P PAUSE \xB7 A/\u2190 LEFT \xB7 S/\u2193 MIDDLE \xB7 D/\u2192 RIGHT \xB7 CLICK A SIDE TO FLIP",
    gameOverKicker: "Color mismatch",
    runTitle: "Run",
    overTitle: "over",
    mismatchDefault: "The disk found the wrong monster.",
    mismatch: "MISMATCH \xB7 {color} needed the {side} monster.",
    newRecord: "New record registered",
    finalScoreLabel: "Score",
    finalBestLabel: "Best",
    finalPhaseLabel: "Phase reached",
    finalLongestStreakLabel: "Longest streak",
    failureLaneLabel: "Failure lane",
    failureReasonLabel: "Failure reason",
    failureWrongSide: "Wrong catcher side",
    failureCatcherFlipping: "Catcher still flipping",
    failureInvalidLane: "Catcher unavailable",
    failureMismatch: "Color mismatch",
    laneUnknown: "\u2014",
    restartButton: "Play again",
    backToMenu: "Main menu",
    restartNote: "Space or Enter also restarts",
    pauseKicker: "Telemetry paused",
    pauseTitle: "Take",
    pauseTitleAccent: "a breath",
    pauseText: "The field is frozen. Resume when you are ready.",
    resumeButton: "Resume",
    pauseNote: "P also toggles pause",
    mobilePause: "Pause",
    mobileResume: "Resume",
    switchToEn: "Switch to English",
    switchToPt: "Switch to Brazilian Portuguese",
    resetStatsLabel: "Reset all game stats",
    resetKicker: "Stats control",
    resetTitle: "Reset",
    resetTitleAccent: "stats?",
    resetText: "Reset all game stats and start over?",
    resetCancel: "Keep stats",
    resetContinue: "Continue",
    resetConfirmKicker: "Final check",
    resetConfirmTitle: "Really",
    resetConfirmTitleAccent: "start over?",
    resetConfirmText: "Is this really what you want? All scores, victories, clear times, and unlocked Endless modes will be cleared.",
    resetBack: "Go back",
    resetConfirm: "Reset stats",
    easyMode: "EASY",
    easyModeDetail: "2 catchers",
    hardMode: "HARD",
    hardModeDetail: "3 catchers",
    difficultyLabel: "Difficulty",
    runTypeLabel: "Mission",
    campaignType: "CAMPAIGN",
    campaignTypeDetail: "Reach the final extraction",
    endlessType: "ENDLESS",
    endlessTypeDetail: "Survive beyond the speed cap",
    endlessLocked: "Win {mode} Campaign to unlock its Endless mode.",
    endlessUnlocked: "Endless is unlocked for {mode}.",
    campaignBestLabel: "Campaign best",
    endlessBestLabel: "Endless best",
    finalExtraction: "Final extraction",
    extractionKicker: "Destination locked",
    extractionTitle: "FINAL EXTRACTION",
    extractionRemaining: "{count} batches remain",
    endlessPhase: "Endless",
    maxSpeed: "MAX",
    missionCompleteKicker: "Final extraction complete",
    missionTitle: "Mission",
    completeAccent: "complete",
    victoryIntro: "{mode} Campaign cleared. Endless mode is now available.",
    clearTimeLabel: "Clear time",
    fastestClearLabel: "Fastest clear",
    totalVictoriesLabel: "Victories",
    replayCampaign: "Replay campaign",
    startEndless: "Start Endless",
    switchDifficulty: "Switch difficulty",
    victoryReplayNote: "Space or Enter replays the campaign",
    modeEasy: "EASY",
    modeHard: "HARD",
    musicLabel: "Music",
    sfxLabel: "SFX",
    audioControls: "Sound controls",
    musicVolumeAria: "Music volume",
    sfxVolumeAria: "Sound effects volume",
    readyToastEasy: "TWO LANES \xB7 GET READY",
    readyToastHard: "THREE LANES \xB7 GET READY",
    paused: "PAUSED",
    flipToast: "FLIP {side} \xB7 {color}",
    collectedToast: "COLLECTED \xB7 {color}",
    waveToast: "PHASE {phase} \xB7 FASTER",
    easy: "EASY",
    hard: "HARD",
    left: "LEFT",
    middle: "MIDDLE",
    right: "RIGHT",
    laneLeft: "A / \u2190 \xB7 FLIP LANE 1",
    laneMiddle: "S / \u2193 \xB7 FLIP LANE 2",
    laneRightEasy: "D / \u2192 \xB7 FLIP LANE 2",
    laneRightHard: "D / \u2192 \xB7 FLIP LANE 3",
    green: "GREEN",
    red: "RED",
    top: "top",
    bottom: "bottom",
    patternPair: "PAIR",
    patternSplit: "SPLIT",
    patternSwap: "SWAP",
    patternMixed: "MIXED SPEED",
    patternTeleport: "TELEPORT",
    patternMystery: "MYSTERY",
    teleporting: "Teleporting",
    patternRapid: "RAPID"
  }),
  "pt-BR": Object.freeze({
    streakLabel: "Sequ\xEAncia",
    finalPhaseLabel: "Fase alcan\xE7ada",
    finalLongestStreakLabel: "Maior sequ\xEAncia",
    failureLaneLabel: "Faixa da falha",
    failureReasonLabel: "Motivo da falha",
    failureWrongSide: "Lado incorreto do capturador",
    failureCatcherFlipping: "Capturador ainda virando",
    failureInvalidLane: "Capturador indispon\xEDvel",
    failureMismatch: "Incompatibilidade de cor",
    laneUnknown: "\u2014",
    documentTitle: "Cosmic Catchers",
    gameAria: "Jogo Cosmic Catchers",
    brandKicker: "Campo arcade / edi\xE7\xE3o desktop",
    gameTitle: "COSMIC CATCHERS",
    cosmicTitle: "Cosmic",
    catchersTitle: "Catchers",
    scoreLabel: "Pontua\xE7\xE3o",
    phaseLabel: "Fase",
    patternLabel: "Padr\xE3o",
    welcomeKicker: "Bem-vindo de volta, piloto",
    readyIntro: "Os discos seguem linhas fixas. Vire cada monstro para a cor correta antes que cheguem ao alvo.",
    readyIntroEasy: "Dois discos seguem linhas fixas. Vire cada monstro para a cor correta antes que cheguem ao alvo.",
    readyIntroHard: "Tr\xEAs discos seguem linhas fixas. Vire os tr\xEAs monstros para a cor correta antes que cheguem aos alvos.",
    greenRuleTitle: "TOPO / VERDE",
    greenRuleText: "O monstro verde captura o disco verde.",
    redRuleTitle: "BAIXO / VERMELHO",
    redRuleText: "O monstro vermelho captura o disco vermelho.",
    startButton: "Come\xE7ar a rodada",
    enteringField: "Entrando no campo c\xF3smico",
    readyNoteEasy: "A / \u2190 vira a faixa esquerda \xB7 D / \u2192 vira a direita",
    readyNoteHard: "A / \u2190 esquerda \xB7 S / \u2193 meio \xB7 D / \u2192 direita",
    helpEasy: "P PAUSA \xB7 A/\u2190 ESQUERDA \xB7 D/\u2192 DIREITA \xB7 CLIQUE EM UMA FAIXA",
    helpHard: "P PAUSA \xB7 A/\u2190 ESQUERDA \xB7 S/\u2193 MEIO \xB7 D/\u2192 DIREITA \xB7 CLIQUE EM UMA FAIXA",
    gameOverKicker: "Incompatibilidade de cor",
    runTitle: "Rodada",
    overTitle: "encerrada",
    mismatchDefault: "O disco encontrou o monstro errado.",
    mismatch: "INCOMPATIBILIDADE \xB7 {color} precisava do monstro {side}.",
    newRecord: "Novo recorde registrado",
    finalScoreLabel: "Pontua\xE7\xE3o",
    finalBestLabel: "Recorde",
    restartButton: "Jogar novamente",
    backToMenu: "Menu principal",
    restartNote: "Espa\xE7o ou Enter tamb\xE9m reinicia",
    pauseKicker: "Telemetria pausada",
    pauseTitle: "Respire",
    pauseTitleAccent: "um pouco",
    pauseText: "O campo est\xE1 congelado. Retome quando estiver pronto.",
    resumeButton: "Continuar",
    pauseNote: "P tamb\xE9m alterna a pausa",
    mobilePause: "Pausar",
    mobileResume: "Continuar",
    switchToEn: "Mudar para ingl\xEAs",
    switchToPt: "Mudar para portugu\xEAs brasileiro",
    resetStatsLabel: "Zerar todas as estat\xEDsticas",
    resetKicker: "Controle de estat\xEDsticas",
    resetTitle: "Zerar",
    resetTitleAccent: "estat\xEDsticas?",
    resetText: "Zerar todas as estat\xEDsticas do jogo e come\xE7ar de novo?",
    resetCancel: "Manter estat\xEDsticas",
    resetContinue: "Continuar",
    resetConfirmKicker: "Última confirma\xE7\xE3o",
    resetConfirmTitle: "Tem certeza",
    resetConfirmTitleAccent: "que quer recome\xE7ar?",
    resetConfirmText: "Essa \xE9 mesmo a sua inten\xE7\xE3o? Todas as pontua\xE7\xF5es, vit\xF3rias, tempos e modos Infinito liberados ser\xE3o apagados.",
    resetBack: "Voltar",
    resetConfirm: "Zerar estat\xEDsticas",
    easyMode: "F\xC1CIL",
    easyModeDetail: "2 capturadores",
    hardMode: "DIF\xCDCIL",
    hardModeDetail: "3 capturadores",
    difficultyLabel: "Dificuldade",
    runTypeLabel: "Miss\xE3o",
    campaignType: "CAMPANHA",
    campaignTypeDetail: "Alcance a extra\xE7\xE3o final",
    endlessType: "INFINITO",
    endlessTypeDetail: "Sobreviva al\xE9m do limite de velocidade",
    endlessLocked: "Ven\xE7a a Campanha no {mode} para liberar o modo Infinito.",
    endlessUnlocked: "O modo Infinito est\xE1 liberado no {mode}.",
    campaignBestLabel: "Recorde da campanha",
    endlessBestLabel: "Recorde infinito",
    finalExtraction: "Extra\xE7\xE3o final",
    extractionKicker: "Destino confirmado",
    extractionTitle: "EXTRA\xC7\xC3O FINAL",
    extractionRemaining: "Restam {count} lotes",
    endlessPhase: "Infinito",
    maxSpeed: "M\xC1X.",
    missionCompleteKicker: "Extra\xE7\xE3o final conclu\xEDda",
    missionTitle: "Miss\xE3o",
    completeAccent: "cumprida",
    victoryIntro: "Campanha no {mode} conclu\xEDda. O modo Infinito foi liberado.",
    clearTimeLabel: "Tempo final",
    fastestClearLabel: "Melhor tempo",
    totalVictoriesLabel: "Vit\xF3rias",
    replayCampaign: "Repetir campanha",
    startEndless: "Iniciar Infinito",
    switchDifficulty: "Trocar dificuldade",
    victoryReplayNote: "Espa\xE7o ou Enter repete a campanha",
    modeEasy: "F\xC1CIL",
    modeHard: "DIF\xCDCIL",
    musicLabel: "M\xFAsica",
    sfxLabel: "Efeitos",
    audioControls: "Controles de som",
    musicVolumeAria: "Volume da m\xFAsica",
    sfxVolumeAria: "Volume dos efeitos",
    readyToastEasy: "DUAS FAIXAS \xB7 PREPARE-SE",
    readyToastHard: "TR\xCAS FAIXAS \xB7 PREPARE-SE",
    paused: "PAUSADO",
    flipToast: "VIRA {side} \xB7 {color}",
    collectedToast: "COLETADO \xB7 {color}",
    waveToast: "FASE {phase} \xB7 MAIS R\xC1PIDO",
    easy: "F\xC1CIL",
    hard: "DIF\xCDCIL",
    left: "ESQUERDA",
    middle: "MEIO",
    right: "DIREITA",
    laneLeft: "A / \u2190 \xB7 VIRAR FAIXA 1",
    laneMiddle: "S / \u2193 \xB7 VIRAR FAIXA 2",
    laneRightEasy: "D / \u2192 \xB7 VIRAR FAIXA 2",
    laneRightHard: "D / \u2192 \xB7 VIRAR FAIXA 3",
    green: "VERDE",
    red: "VERMELHO",
    top: "em cima",
    bottom: "embaixo",
    patternPair: "DUPLO",
    patternSplit: "DIVIDIDO",
    patternSwap: "TROCA",
    patternMixed: "VELOCIDADE MISTA",
    patternTeleport: "TELEPORTE",
    patternMystery: "MISTÉRIO",
    teleporting: "Teleportando",
    patternRapid: "R\xC1PIDO"
  })
});
function translate(language, key, variables = {}) {
  const table = TRANSLATIONS[language] || TRANSLATIONS.en;
  let text = table[key] || TRANSLATIONS.en[key] || key;
  Object.entries(variables).forEach(([name, value]) => {
    text = text.split(`{${name}}`).join(String(value));
  });
  return text;
}
function localizeDocument(language, root = document) {
  root.documentElement.lang = language;
  root.title = translate(language, "documentTitle");
  root.querySelectorAll("[data-i18n]").forEach((element) => {
    element.textContent = translate(language, element.dataset.i18n);
  });
}
export { TRANSLATIONS, localizeDocument, translate };
