import { build, transform } from "esbuild";
import { copyFile, mkdir, readFile, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { createHash } from "node:crypto";

const root = path.resolve(import.meta.dirname, "..");
const dist = path.join(root, "dist");
const productionFilename = "## JOGUE AQUI.html";
const testBuild = process.argv.includes("--test");
const screenNames = ["ready", "reset", "entry", "gameover", "pause", "extraction", "victory"];
const styleNames = ["base", "layout", "screens", "responsive"];

async function readSource(relativePath) {
  return readFile(path.join(root, relativePath), "utf8");
}

async function buildJavaScript() {
  const result = await build({
    entryPoints: [path.join(root, "src", "js", "main.js")],
    bundle: true,
    define: { __COSMIC_TEST__: testBuild ? "true" : "false" },
    format: "iife",
    legalComments: "eof",
    minify: !testBuild,
    platform: "browser",
    target: ["es2020"],
    treeShaking: true,
    write: false
  });
  return result.outputFiles[0].text.replace(/<\/script/gi, "<\\/script");
}

async function buildStyles() {
  const sources = await Promise.all(styleNames.map((name) => readSource(`src/styles/${name}.css`)));
  const result = await transform(sources.join("\n"), { loader: "css", minify: !testBuild });
  return result.code.trim().replace(/<\/style/gi, "<\\/style");
}

async function assembleHtml() {
  let html = await readSource("src/index.template.html");
  const [styles, script, screens] = await Promise.all([
    buildStyles(),
    buildJavaScript(),
    Promise.all(screenNames.map((name) => readSource(`src/screens/${name}.html`)))
  ]);
  html = html.replace("{{STYLES}}", () => styles).replace("{{SCRIPT}}", () => script);
  screenNames.forEach((name, index) => {
    html = html.replace(`{{SCREEN_${name.toUpperCase()}}}`, () => screens[index].trim());
  });
  const unresolved = html.match(/\{\{[A-Z_]+\}\}/g);
  if (unresolved) throw new Error(`Unresolved build-time template tokens: ${[...new Set(unresolved)].join(", ")}`);
  return `<!-- Generated by npm run build. Edit src/, never this file. -->\n${html.trim()}\n`;
}

function sha256(contents) {
  return createHash("sha256").update(contents).digest("hex");
}

async function locateAsset(name) {
  const canonical = path.join(root, "assets", name);
  try {
    await readFile(canonical);
    return canonical;
  } catch {
    return path.join(root, name);
  }
}

await rm(dist, { recursive: true, force: true });
await mkdir(dist, { recursive: true });
const html = await assembleHtml();
const outputName = testBuild ? "## JOGUE AQUI.test.html" : productionFilename;
await writeFile(path.join(dist, outputName), html, "utf8");
if (!testBuild) await writeFile(path.join(root, productionFilename), html, "utf8");

const manifest = JSON.parse(await readSource("baseline-manifest.json"));
for (const asset of manifest.assets) {
  await copyFile(await locateAsset(asset.name), path.join(dist, asset.name));
}

const checksumLines = [];
for (const name of [outputName, ...manifest.assets.map((asset) => asset.name)]) {
  const contents = await readFile(path.join(dist, name));
  checksumLines.push(`${sha256(contents)}  ${name}`);
}
await writeFile(path.join(dist, "SHA256SUMS"), checksumLines.join("\n") + "\n", "utf8");
const canonicalNote = testBuild ? "" : ` and refreshed ${productionFilename}`;
console.log(`Built dist/${outputName}${canonicalNote} (${Buffer.byteLength(html)} bytes).`);
